### ISSUE TITLE
Spécifier API

### ISSUE THREAD

**Issue by natthamonng** [formation-dwwm/graphcalc-js#6]
- fonctions
-variables

utilisées et définies par le programme

**Tasks**
- [x] Write doc
- [x] Translate txt to markdown

**Acceptance Criteria**
- [x] Documentation disponible pour tous
- [x] Documentation formatée (markdown)

**Comment by natthamonng** [comment]
Spécif / doc disponible dans README:

https://github.com/formation-dwwm/graphcalc-js/blob/master/readme.txt

**Comment by natthamonng** [comment]
- [x] Write doc
- [ ] Translate txt to markdown

**Comment by LiSplib** [comment]
translate txt to md ok
